name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Adopt JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          architecture: x64
      - name: Build with Maven
        run: mvn --batch-mode verify -P release
        env:
          SIGN_KEY: ${{ secrets.TEST_CODE_SIGNING_SECRET_KEY }}
          SIGN_KEY_PASS: ${{ secrets.TEST_CODE_SIGNING_SECRET_KEY_PASS }}
